# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisallowedHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Cr\xc3\xa9\xc3\xa9 le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name=b'Modifi\xc3\xa9 le')),
                ('http_host', models.CharField(blank=True, max_length=254, null=True, verbose_name='HTTP_HOST')),
                ('remote_addr', models.CharField(blank=True, max_length=254, null=True, verbose_name='REMOTE_ADDR')),
                ('http_x_forwarded_for', models.CharField(blank=True, max_length=254, null=True, verbose_name='HTTP_X_FORWARDED_FOR')),
                ('request_uri', models.CharField(blank=True, max_length=254, null=True, verbose_name='REQUEST_URI')),
                ('request_method', models.CharField(blank=True, max_length=254, null=True, verbose_name='REQUEST_METHOD')),
                ('query_string', models.CharField(blank=True, max_length=254, null=True, verbose_name='QUERY_STRING')),
                ('path_info', models.CharField(blank=True, max_length=254, null=True, verbose_name='PATH_INFO')),
                ('http_user_agent', models.CharField(blank=True, max_length=254, null=True, verbose_name='HTTP_USER_AGENT')),
                ('html_report', models.TextField(blank=True, null=True, verbose_name='HTML report')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'workon_security_disallowedhost',
                'verbose_name': 'Selection',
                'verbose_name_plural': 'Selections',
            },
        ),
    ]
