# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workon_security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disallowedhost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Intrusion', 'verbose_name_plural': 'Intrusions'},
        ),
    ]
