# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workon', '0015_auto_20160115_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='template',
            field=models.TextField(help_text='\n        Pour inserer un lien d\'activation de compte utilisez : <b>*|ACTIVATE_URL|*</b>.<br />\n        exemple : <b>&lt;a href="*|ACTIVATE_URL|*"&gt;Cliquez ici pour votre connecter&lt;/a&gt;</b>\n    ', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='googleapisettings',
            name='account_key_file',
            field=models.FileField(blank=True, help_text='\n\n            Allez sur <a target="_blank" href="https://console.developers.google.com/apis/">https://console.developers.google.com/apis/</a>\n            <br/>\n            Cliquer sur identifiants\n            <br/>\n            Cliquer sur nouveaux identifiants\n            <br/>\n            Cliquer sur Cr\xe9\xe9r un compte de service\n            <br/>\n            Nommer le compte, copier/coller l\'ID du compte de service, puis cocher JSON\n            <br/>\n            Cliquer sur Cr\xe9\xe9r\n            <br/>\n            Ajouter le compte (ID copier/coller) en lecture seule dans votre compte analytics (<a target="_blank" href="https://www.google.com/analytics/web/">https://www.google.com/analytics/web/</a>)\n            <br/>\n            Puis ajouter ici le fichier telecharg\xe9 depuis la page Google Developpers Console (apr\xe9s avoir cliqu\xe9 sur Cr\xe9\xe9r)\n\n        ', null=True, upload_to=b'workon/googleapisettings/', verbose_name='Adresse email'),
        ),
    ]
