# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workon', '0017_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCard',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
                ('user_email', models.CharField(max_length=254, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
                ('is_executed', models.BooleanField(default=False, verbose_name='Execut\xe9 ?')),
                ('type', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Type')),
                ('exec_errors', models.TextField(blank=True, null=True, verbose_name='Import errors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='workon.StripeCharge')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='workon.StripeCustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workon.StripeInvoice')),
            ],
        ),
        migrations.CreateModel(
            name='StripePlan',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workon.StripeCustomer')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workon.StripePlan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeTransfer',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date cr\xe9ation')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date mise \xe0 jour')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID Stripe')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data Stripe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stripeinvoiceitem',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workon.StripePlan'),
        ),
        migrations.AddField(
            model_name='stripeinvoiceitem',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workon.StripeSubscription'),
        ),
        migrations.AddField(
            model_name='stripeinvoice',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workon.StripeSubscription'),
        ),
        migrations.AddField(
            model_name='stripecharge',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='workon.StripeCustomer'),
        ),
        migrations.AddField(
            model_name='stripecharge',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='workon.StripeInvoice'),
        ),
    ]
