# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workon', '0019_auto_20160218_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Cr\xe9\xe9 le')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifi\xe9 le')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Token d'activation")),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilis\xe9 ?')),
                ('expiration_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'expiration")),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name="date d'activation")),
            ],
            options={
                'ordering': ('created_date', 'activation_date'),
                'verbose_name': "Cl\xe9 d'activation",
                'verbose_name_plural': "Cl\xe9s d'activation",
            },
        ),
        migrations.DeleteModel(
            name='EmailingUserActivationToken',
        ),
    ]
