# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workon', '0020_auto_20160314_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterUniqueTogether(
            name='activationtoken',
            unique_together=set([('email', 'token')]),
        ),
    ]
