# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20160611_0746'),
        ('workon', '0022_auto_20160510_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailingTestEmail',
        ),
        migrations.RemoveField(
            model_name='emailingtransaction',
            name='emailing',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='user',
        ),
        migrations.DeleteModel(
            name='Emailing',
        ),
        migrations.DeleteModel(
            name='EmailingTransaction',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
