# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Cr\xc3\xa9\xc3\xa9 le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name=b'Modifi\xc3\xa9 le')),
                ('name', models.CharField(max_length=254, verbose_name='Nom')),
                ('description', models.TextField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('ids', models.TextField(default=b'', verbose_name='ids')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'workon_selection_selection',
                'verbose_name': 'Selection',
                'verbose_name_plural': 'Selections',
            },
        ),
    ]
